// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`, `fetch_block_time`, `run_full_sync_internal`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MempoolObserverState`

/// Set the desired sync mode. 0=none, 1=foreground, 2=background.
/// The running sync loop checks this each batch and exits if mismatched.
void setSyncMode({required int mode}) =>
    RustLib.instance.api.crateApiSyncSetSyncMode(mode: mode);

/// Get the current desired sync mode.
int getSyncMode() => RustLib.instance.api.crateApiSyncGetSyncMode();

/// Start a full sync. Streams progress events to Dart via StreamSink.
/// mode: 1=foreground, 2=background. Sync exits if desired mode changes.
Stream<ApiSyncProgressEvent> startFullSync({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required int mode,
}) => RustLib.instance.api.crateApiSyncStartFullSync(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  mode: mode,
);

/// Blocking sync entrypoint that uses the same API-layer network parsing,
/// desired-mode globals, and running guard as `start_full_sync`, but without
/// a StreamSink. Used by Rust integration tests that want to stay on the
/// public API surface.
Future<void> runFullSyncBlocking({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required int mode,
}) => RustLib.instance.api.crateApiSyncRunFullSyncBlocking(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  mode: mode,
);

/// Cancel a running full sync.
void cancelFullSync() => RustLib.instance.api.crateApiSyncCancelFullSync();

/// Check whether a sync cancel has been requested.
bool isSyncCancelRequested() =>
    RustLib.instance.api.crateApiSyncIsSyncCancelRequested();

/// Check if a sync is currently running.
bool isSyncRunning() => RustLib.instance.api.crateApiSyncIsSyncRunning();

/// Start the background mempool observer.
///
/// Blocks until [`stop_mempool_observer`] is called or the
/// observer returns on an unrecoverable setup error. Every
/// incoming mempool tx that can be parsed is pushed to `sink` as
/// an [`ApiMempoolTxEvent`].
///
/// The FRB layer runs this on the Rust isolate thread pool, so
/// Dart can `await` the call while the observer keeps polling
/// lightwalletd in the background. Dart is expected to fire this
/// alongside `start_full_sync` and call `stop_mempool_observer`
/// alongside `cancel_full_sync` — the two lifecycles are parallel
/// but separately controlled (intentional: the same bug in one
/// path must not silently take down the other).
Stream<ApiMempoolTxEvent> startMempoolObserver({
  required String dbPath,
  required String network,
  required String lightwalletdUrl,
}) => RustLib.instance.api.crateApiSyncStartMempoolObserver(
  dbPath: dbPath,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
);

/// Ask the running mempool observer to exit at the next cancel
/// check (inside the 100ms sleep slices or between stream
/// messages). Safe to call when no observer is running — the
/// stored cancel token is `None` in that case and this becomes a
/// no-op.
void stopMempoolObserver() =>
    RustLib.instance.api.crateApiSyncStopMempoolObserver();

/// Check whether the mempool observer task is currently running.
bool isMempoolObserverRunning() =>
    RustLib.instance.api.crateApiSyncIsMempoolObserverRunning();

Future<void> updateChainTip({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncUpdateChainTip(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<SubtreeIndices> getNextSubtreeIndices({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetNextSubtreeIndices(
  dbPath: dbPath,
  network: network,
);

Future<void> putSubtreeRoots({
  required String dbPath,
  required String network,
  required BigInt saplingStartIndex,
  required List<SubtreeRoot> saplingRoots,
  required BigInt orchardStartIndex,
  required List<SubtreeRoot> orchardRoots,
}) => RustLib.instance.api.crateApiSyncPutSubtreeRoots(
  dbPath: dbPath,
  network: network,
  saplingStartIndex: saplingStartIndex,
  saplingRoots: saplingRoots,
  orchardStartIndex: orchardStartIndex,
  orchardRoots: orchardRoots,
);

Future<List<ScanRangeInfo>> suggestScanRanges({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncSuggestScanRanges(
  dbPath: dbPath,
  network: network,
);

Future<void> writeBlockMetadata({
  required String cachePath,
  required List<BlockMetaInfo> blocks,
}) => RustLib.instance.api.crateApiSyncWriteBlockMetadata(
  cachePath: cachePath,
  blocks: blocks,
);

Future<ScanResult> scanBlocks({
  required String dbPath,
  required String cachePath,
  required String network,
  required BigInt fromHeight,
  required String treeStateNetwork,
  required BigInt treeStateHeight,
  required String treeStateHash,
  required int treeStateTime,
  required String treeStateSaplingTree,
  required String treeStateOrchardTree,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSyncScanBlocks(
  dbPath: dbPath,
  cachePath: cachePath,
  network: network,
  fromHeight: fromHeight,
  treeStateNetwork: treeStateNetwork,
  treeStateHeight: treeStateHeight,
  treeStateHash: treeStateHash,
  treeStateTime: treeStateTime,
  treeStateSaplingTree: treeStateSaplingTree,
  treeStateOrchardTree: treeStateOrchardTree,
  limit: limit,
);

Future<SyncProgress> getSyncStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetSyncStatus(
  dbPath: dbPath,
  network: network,
);

Future<WalletBalance> getBalance({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetBalance(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<BigInt> rewindToHeight({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncRewindToHeight(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<AddressValidationResult> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiSyncValidateAddress(address: address);

/// Step 1: Propose a transfer. Returns proposal info including whether Sapling params are needed.
Future<ProposalResult> proposeSend({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncProposeSend(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Estimate the fee for a transfer without storing a proposal.
Future<BigInt> estimateFee({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncEstimateFee(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Estimate the maximum recipient amount for the current recipient and memo.
Future<SendMaxEstimateResult> estimateSendMax({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  String? memo,
}) => RustLib.instance.api.crateApiSyncEstimateSendMax(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  memo: memo,
);

/// Step 2: Execute a previously proposed transfer and broadcast to the network.
/// spend_params_path and output_params_path are required only if needs_sapling_params was true.
Future<String> executeProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required BigInt proposalId,
  required String sendFlowId,
  required List<int> seed,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExecuteProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
  seed: seed,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// Dry-run transparent shielding without creating or broadcasting a transaction.
Future<ShieldTransparentStatus> getShieldTransparentStatus({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetShieldTransparentStatus(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Shield spendable transparent funds into the account's shielded balance.
/// Software-account only; hardware shielding will be added separately through
/// the PCZT flow.
Future<ShieldTransparentResult> shieldTransparentBalance({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required List<int> seed,
}) => RustLib.instance.api.crateApiSyncShieldTransparentBalance(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  seed: seed,
);

Future<String> getNextAvailableAddress({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetNextAvailableAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<List<TxDataRequest>> getTransactionDataRequests({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetTransactionDataRequests(
  dbPath: dbPath,
  network: network,
);

Future<void> decryptAndStoreTransaction({
  required String dbPath,
  required String network,
  required List<int> txBytes,
  BigInt? minedHeight,
}) => RustLib.instance.api.crateApiSyncDecryptAndStoreTransaction(
  dbPath: dbPath,
  network: network,
  txBytes: txBytes,
  minedHeight: minedHeight,
);

Future<void> setTransactionStatus({
  required String dbPath,
  required String network,
  required String txidHex,
  required PlatformInt64 status,
}) => RustLib.instance.api.crateApiSyncSetTransactionStatus(
  dbPath: dbPath,
  network: network,
  txidHex: txidHex,
  status: status,
);

Future<List<TransactionInfo>> getTransactionHistory({
  required String dbPath,
  required String network,
  int? limit,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetTransactionHistory(
  dbPath: dbPath,
  network: network,
  limit: limit,
  accountUuid: accountUuid,
);

Future<BigInt> getExportBirthdayHeight({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetExportBirthdayHeight(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<BigInt> getBlockTime({
  required String lightwalletdUrl,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncGetBlockTime(
  lightwalletdUrl: lightwalletdUrl,
  height: height,
);

TransactionDetail getTransactionDetail({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String txidHex,
  required String txKind,
}) => RustLib.instance.api.crateApiSyncGetTransactionDetail(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  txidHex: txidHex,
  txKind: txKind,
);

String getBlocksDir({required String cachePath}) =>
    RustLib.instance.api.crateApiSyncGetBlocksDir(cachePath: cachePath);

/// Create a PCZT from a stored proposal for hardware wallet signing.
Future<Uint8List> createPcztFromProposal({
  required String dbPath,
  required String network,
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncCreatePcztFromProposal(
  dbPath: dbPath,
  network: network,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Release a stored proposal without executing it. Called by the Dart send
/// flow when the user cancels before `create_pczt_from_proposal` so the
/// proposal ID cannot be replayed. Idempotent.
Future<void> discardProposal({
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncDiscardProposal(
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Add Orchard (and Sapling if needed) proofs to a PCZT locally. The output
/// is the "PCZT with proofs" half that is later combined with the signed PCZT
/// returned by the hardware wallet.
///
/// `spend_params_path` and `output_params_path` are only consulted when the
/// PCZT has a non-empty Sapling bundle (e.g. sending to a Sapling-only
/// recipient). Orchard-only sends can pass `None` for both. The caller is
/// responsible for ensuring the referenced files exist — the `proposal
/// .needsSaplingParams` flag on the propose result already tells the Dart
/// layer when it needs to download them.
Future<Uint8List> addProofsToPczt({
  required List<int> pcztBytes,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncAddProofsToPczt(
  pcztBytes: pcztBytes,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// Redact information from a PCZT that the hardware signer does not need
/// (witnesses, proprietary metadata). The returned bytes are what is sent
/// to the Keystone device for signing.
Future<Uint8List> redactPcztForSigner({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncRedactPcztForSigner(pcztBytes: pcztBytes);

/// Combine a PCZT-with-proofs and a PCZT-with-signatures, extract the final
/// transaction, store it in the wallet DB, and broadcast it to lightwalletd.
/// Returns the txid.
///
/// `spend_params_path` / `output_params_path` are required whenever the
/// combined PCZT has a non-empty Sapling bundle (e.g. the original proposal
/// had `needsSaplingParams == true`). They are used both to verify the
/// extracted transaction in-memory before broadcast and by
/// `extract_and_store_transaction_from_pczt` after broadcast. Orchard-only
/// sends can pass `None` for both. Mirrors the `add_proofs_to_pczt`
/// contract: if you needed to supply params there, you need them here too.
Future<String> extractAndBroadcastPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required List<int> pcztWithProofsBytes,
  required List<int> pcztWithSignaturesBytes,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExtractAndBroadcastPczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  pcztWithProofsBytes: pcztWithProofsBytes,
  pcztWithSignaturesBytes: pcztWithSignaturesBytes,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

class AddressValidationResult {
  final bool isValid;
  final String addressType;

  const AddressValidationResult({
    required this.isValid,
    required this.addressType,
  });

  @override
  int get hashCode => isValid.hashCode ^ addressType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressValidationResult &&
          runtimeType == other.runtimeType &&
          isValid == other.isValid &&
          addressType == other.addressType;
}

/// Event emitted by the mempool observer when a transaction
/// appears on lightwalletd's mempool stream. Mirrored one-to-one
/// from `sync_engine::mempool::MempoolTxEvent` for FRB codegen.
class ApiMempoolTxEvent {
  /// Lower-case hex of the tx id.
  final String txidHex;

  /// `true` when the wallet DB already has this txid in its
  /// `transactions` table with `mined_height IS NULL`. Dart
  /// uses this flag to decide whether to refresh balance +
  /// history immediately.
  final bool matched;

  const ApiMempoolTxEvent({required this.txidHex, required this.matched});

  @override
  int get hashCode => txidHex.hashCode ^ matched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMempoolTxEvent &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          matched == other.matched;
}

/// Progress event streamed to Dart during sync.
class ApiSyncProgressEvent {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final double percentage;

  /// UI-only smoothed progress target. Dart increments toward this
  /// assuming one virtual block per 500ms, capped at the next batch.
  final double displayTargetPercentage;
  final BigInt displayTargetBlocks;
  final bool isSyncing;
  final bool isComplete;
  final bool hasNewTx;

  /// Current sync phase: `"download"`, `"scan"`, `"enhance"`, or
  /// `""` (completion / unspecified).
  final String phase;

  const ApiSyncProgressEvent({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.percentage,
    required this.displayTargetPercentage,
    required this.displayTargetBlocks,
    required this.isSyncing,
    required this.isComplete,
    required this.hasNewTx,
    required this.phase,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^
      chainTipHeight.hashCode ^
      percentage.hashCode ^
      displayTargetPercentage.hashCode ^
      displayTargetBlocks.hashCode ^
      isSyncing.hashCode ^
      isComplete.hashCode ^
      hasNewTx.hashCode ^
      phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSyncProgressEvent &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          percentage == other.percentage &&
          displayTargetPercentage == other.displayTargetPercentage &&
          displayTargetBlocks == other.displayTargetBlocks &&
          isSyncing == other.isSyncing &&
          isComplete == other.isComplete &&
          hasNewTx == other.hasNewTx &&
          phase == other.phase;
}

class BlockMetaInfo {
  final BigInt height;
  final Uint8List hash;
  final int time;
  final int saplingOutputsCount;
  final int orchardActionsCount;

  const BlockMetaInfo({
    required this.height,
    required this.hash,
    required this.time,
    required this.saplingOutputsCount,
    required this.orchardActionsCount,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      hash.hashCode ^
      time.hashCode ^
      saplingOutputsCount.hashCode ^
      orchardActionsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockMetaInfo &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          hash == other.hash &&
          time == other.time &&
          saplingOutputsCount == other.saplingOutputsCount &&
          orchardActionsCount == other.orchardActionsCount;
}

class ProposalResult {
  final BigInt proposalId;
  final bool needsSaplingParams;
  final BigInt feeZatoshi;

  const ProposalResult({
    required this.proposalId,
    required this.needsSaplingParams,
    required this.feeZatoshi,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^ needsSaplingParams.hashCode ^ feeZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          needsSaplingParams == other.needsSaplingParams &&
          feeZatoshi == other.feeZatoshi;
}

class ScanRangeInfo {
  final BigInt start;
  final BigInt end;
  final int priority;

  const ScanRangeInfo({
    required this.start,
    required this.end,
    required this.priority,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRangeInfo &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          priority == other.priority;
}

class ScanResult {
  final BigInt blocksScanned;

  const ScanResult({required this.blocksScanned});

  @override
  int get hashCode => blocksScanned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          blocksScanned == other.blocksScanned;
}

class SendMaxEstimateResult {
  final BigInt amountZatoshi;
  final BigInt feeZatoshi;
  final bool needsSaplingParams;

  const SendMaxEstimateResult({
    required this.amountZatoshi,
    required this.feeZatoshi,
    required this.needsSaplingParams,
  });

  @override
  int get hashCode =>
      amountZatoshi.hashCode ^
      feeZatoshi.hashCode ^
      needsSaplingParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendMaxEstimateResult &&
          runtimeType == other.runtimeType &&
          amountZatoshi == other.amountZatoshi &&
          feeZatoshi == other.feeZatoshi &&
          needsSaplingParams == other.needsSaplingParams;
}

class ShieldTransparentResult {
  final String txids;
  final BigInt feeZatoshi;
  final BigInt shieldedZatoshi;

  const ShieldTransparentResult({
    required this.txids,
    required this.feeZatoshi,
    required this.shieldedZatoshi,
  });

  @override
  int get hashCode =>
      txids.hashCode ^ feeZatoshi.hashCode ^ shieldedZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShieldTransparentResult &&
          runtimeType == other.runtimeType &&
          txids == other.txids &&
          feeZatoshi == other.feeZatoshi &&
          shieldedZatoshi == other.shieldedZatoshi;
}

class ShieldTransparentStatus {
  final bool canShield;
  final BigInt feeZatoshi;
  final BigInt shieldedZatoshi;
  final String reason;

  const ShieldTransparentStatus({
    required this.canShield,
    required this.feeZatoshi,
    required this.shieldedZatoshi,
    required this.reason,
  });

  @override
  int get hashCode =>
      canShield.hashCode ^
      feeZatoshi.hashCode ^
      shieldedZatoshi.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShieldTransparentStatus &&
          runtimeType == other.runtimeType &&
          canShield == other.canShield &&
          feeZatoshi == other.feeZatoshi &&
          shieldedZatoshi == other.shieldedZatoshi &&
          reason == other.reason;
}

class SubtreeIndices {
  final BigInt nextSapling;
  final BigInt nextOrchard;

  const SubtreeIndices({required this.nextSapling, required this.nextOrchard});

  @override
  int get hashCode => nextSapling.hashCode ^ nextOrchard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeIndices &&
          runtimeType == other.runtimeType &&
          nextSapling == other.nextSapling &&
          nextOrchard == other.nextOrchard;
}

class SubtreeRoot {
  final BigInt completingBlockHeight;
  final Uint8List rootHash;

  const SubtreeRoot({
    required this.completingBlockHeight,
    required this.rootHash,
  });

  @override
  int get hashCode => completingBlockHeight.hashCode ^ rootHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeRoot &&
          runtimeType == other.runtimeType &&
          completingBlockHeight == other.completingBlockHeight &&
          rootHash == other.rootHash;
}

class SyncProgress {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final bool isSyncing;

  const SyncProgress({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.isSyncing,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^ chainTipHeight.hashCode ^ isSyncing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          isSyncing == other.isSyncing;
}

class TransactionDetail {
  final String txidHex;
  final String txKind;
  final String? primaryAddress;
  final String? memo;
  final List<TransactionDetailOutput> outputs;

  const TransactionDetail({
    required this.txidHex,
    required this.txKind,
    this.primaryAddress,
    this.memo,
    required this.outputs,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      txKind.hashCode ^
      primaryAddress.hashCode ^
      memo.hashCode ^
      outputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDetail &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          txKind == other.txKind &&
          primaryAddress == other.primaryAddress &&
          memo == other.memo &&
          outputs == other.outputs;
}

class TransactionDetailOutput {
  final String? address;
  final BigInt amountZatoshi;
  final String pool;

  const TransactionDetailOutput({
    this.address,
    required this.amountZatoshi,
    required this.pool,
  });

  @override
  int get hashCode => address.hashCode ^ amountZatoshi.hashCode ^ pool.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDetailOutput &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amountZatoshi == other.amountZatoshi &&
          pool == other.pool;
}

class TransactionInfo {
  final String txidHex;
  final BigInt minedHeight;
  final bool expiredUnmined;
  final PlatformInt64 accountBalanceDelta;
  final BigInt fee;
  final BigInt blockTime;
  final bool isTransparent;
  final String txKind;
  final BigInt displayAmount;
  final String displayPool;
  final BigInt createdTime;

  const TransactionInfo({
    required this.txidHex,
    required this.minedHeight,
    required this.expiredUnmined,
    required this.accountBalanceDelta,
    required this.fee,
    required this.blockTime,
    required this.isTransparent,
    required this.txKind,
    required this.displayAmount,
    required this.displayPool,
    required this.createdTime,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      minedHeight.hashCode ^
      expiredUnmined.hashCode ^
      accountBalanceDelta.hashCode ^
      fee.hashCode ^
      blockTime.hashCode ^
      isTransparent.hashCode ^
      txKind.hashCode ^
      displayAmount.hashCode ^
      displayPool.hashCode ^
      createdTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionInfo &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          minedHeight == other.minedHeight &&
          expiredUnmined == other.expiredUnmined &&
          accountBalanceDelta == other.accountBalanceDelta &&
          fee == other.fee &&
          blockTime == other.blockTime &&
          isTransparent == other.isTransparent &&
          txKind == other.txKind &&
          displayAmount == other.displayAmount &&
          displayPool == other.displayPool &&
          createdTime == other.createdTime;
}

class TxDataRequest {
  final String requestType;
  final String? txid;
  final String? address;
  final BigInt? blockRangeStart;
  final BigInt? blockRangeEnd;

  const TxDataRequest({
    required this.requestType,
    this.txid,
    this.address,
    this.blockRangeStart,
    this.blockRangeEnd,
  });

  @override
  int get hashCode =>
      requestType.hashCode ^
      txid.hashCode ^
      address.hashCode ^
      blockRangeStart.hashCode ^
      blockRangeEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxDataRequest &&
          runtimeType == other.runtimeType &&
          requestType == other.requestType &&
          txid == other.txid &&
          address == other.address &&
          blockRangeStart == other.blockRangeStart &&
          blockRangeEnd == other.blockRangeEnd;
}

class WalletBalance {
  final BigInt transparent;
  final BigInt sapling;
  final BigInt orchard;
  final BigInt transparentPending;
  final BigInt saplingPending;
  final BigInt orchardPending;

  /// Sum of spendable shielded balances. Use this for "available to send".
  final BigInt spendable;

  /// Sum of spendable + pending balances across all pools. Use this for "total holdings".
  final BigInt total;

  const WalletBalance({
    required this.transparent,
    required this.sapling,
    required this.orchard,
    required this.transparentPending,
    required this.saplingPending,
    required this.orchardPending,
    required this.spendable,
    required this.total,
  });

  @override
  int get hashCode =>
      transparent.hashCode ^
      sapling.hashCode ^
      orchard.hashCode ^
      transparentPending.hashCode ^
      saplingPending.hashCode ^
      orchardPending.hashCode ^
      spendable.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalance &&
          runtimeType == other.runtimeType &&
          transparent == other.transparent &&
          sapling == other.sapling &&
          orchard == other.orchard &&
          transparentPending == other.transparentPending &&
          saplingPending == other.saplingPending &&
          orchardPending == other.orchardPending &&
          spendable == other.spendable &&
          total == other.total;
}
