// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`

/// Get the latest block height from lightwalletd.
Future<BigInt> getLatestBlockHeight({required String lightwalletdUrl}) =>
    RustLib.instance.api.crateApiWalletGetLatestBlockHeight(
      lightwalletdUrl: lightwalletdUrl,
    );

/// Get the lightwalletd chain name ("main" or "test") for endpoint validation.
Future<String> getLightwalletdChainName({required String lightwalletdUrl}) =>
    RustLib.instance.api.crateApiWalletGetLightwalletdChainName(
      lightwalletdUrl: lightwalletdUrl,
    );

/// Create a new Zcash wallet with a fresh mnemonic.
/// birthday_height should be the current chain tip (from get_latest_block_height).
Future<WalletCreationResult> createWallet({
  required String network,
  required String dbPath,
  BigInt? birthdayHeight,
  String? accountName,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  network: network,
  dbPath: dbPath,
  birthdayHeight: birthdayHeight,
  accountName: accountName,
);

/// Import an existing wallet from a mnemonic phrase.
Future<WalletImportResult> importWallet({
  required String mnemonic,
  BigInt? birthdayHeight,
  required String network,
  required String dbPath,
  String? accountName,
}) => RustLib.instance.api.crateApiWalletImportWallet(
  mnemonic: mnemonic,
  birthdayHeight: birthdayHeight,
  network: network,
  dbPath: dbPath,
  accountName: accountName,
);

/// Add an additional account to an existing wallet database.
Future<AccountCreationResult> addAccount({
  required String dbPath,
  required String network,
  required String name,
  required String mnemonic,
  BigInt? birthdayHeight,
}) => RustLib.instance.api.crateApiWalletAddAccount(
  dbPath: dbPath,
  network: network,
  name: name,
  mnemonic: mnemonic,
  birthdayHeight: birthdayHeight,
);

/// Import a hardware wallet account using a UFVK (no mnemonic/seed needed).
Future<AccountCreationResult> importHardwareAccount({
  required String dbPath,
  required String network,
  required String name,
  required String ufvkString,
  required List<int> seedFingerprint,
  required int zip32Index,
  BigInt? birthdayHeight,
}) => RustLib.instance.api.crateApiWalletImportHardwareAccount(
  dbPath: dbPath,
  network: network,
  name: name,
  ufvkString: ufvkString,
  seedFingerprint: seedFingerprint,
  zip32Index: zip32Index,
  birthdayHeight: birthdayHeight,
);

/// List all accounts in the wallet database.
Future<List<AccountInfo>> listAccounts({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiWalletListAccounts(
  dbPath: dbPath,
  network: network,
);

/// Get the Unified Address for a specific account (or first account if uuid is None).
Future<String> getUnifiedAddress({
  required String dbPath,
  required String network,
  String? accountUuid,
}) => RustLib.instance.api.crateApiWalletGetUnifiedAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Generate a new 24-word BIP-39 mnemonic phrase.
String generateMnemonic() =>
    RustLib.instance.api.crateApiWalletGenerateMnemonic();

/// Get the BIP-39 English word list used for mnemonic validation.
List<String> mnemonicWordList() =>
    RustLib.instance.api.crateApiWalletMnemonicWordList();

/// Check if a wallet database exists at the given path.
bool walletExists({required String dbPath}) =>
    RustLib.instance.api.crateApiWalletWalletExists(dbPath: dbPath);

/// Validate a mnemonic phrase (checks word count and validity).
bool validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletValidateMnemonic(mnemonic: mnemonic);

/// Derive seed bytes from a mnemonic phrase.
/// Returns 64 raw bytes. The caller should treat these as sensitive.
Future<Uint8List> deriveSeed({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletDeriveSeed(mnemonic: mnemonic);

/// Get the transparent address for a specific account (or first account if uuid is None).
Future<String> getTransparentAddress({
  required String dbPath,
  required String network,
  String? accountUuid,
}) => RustLib.instance.api.crateApiWalletGetTransparentAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Result of adding an account to an existing wallet.
class AccountCreationResult {
  final String accountUuid;
  final String unifiedAddress;

  const AccountCreationResult({
    required this.accountUuid,
    required this.unifiedAddress,
  });

  @override
  int get hashCode => accountUuid.hashCode ^ unifiedAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountCreationResult &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          unifiedAddress == other.unifiedAddress;
}

/// Account info returned by list_accounts.
class AccountInfo {
  final String uuid;
  final String name;
  final String unifiedAddress;

  const AccountInfo({
    required this.uuid,
    required this.name,
    required this.unifiedAddress,
  });

  @override
  int get hashCode => uuid.hashCode ^ name.hashCode ^ unifiedAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          unifiedAddress == other.unifiedAddress;
}

/// Result of wallet creation, containing the mnemonic, unified address, and account UUID.
class WalletCreationResult {
  final String mnemonic;
  final String unifiedAddress;
  final String accountUuid;

  const WalletCreationResult({
    required this.mnemonic,
    required this.unifiedAddress,
    required this.accountUuid,
  });

  @override
  int get hashCode =>
      mnemonic.hashCode ^ unifiedAddress.hashCode ^ accountUuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreationResult &&
          runtimeType == other.runtimeType &&
          mnemonic == other.mnemonic &&
          unifiedAddress == other.unifiedAddress &&
          accountUuid == other.accountUuid;
}

/// Result of wallet import, containing the unified address and account UUID.
class WalletImportResult {
  final String unifiedAddress;
  final String accountUuid;

  const WalletImportResult({
    required this.unifiedAddress,
    required this.accountUuid,
  });

  @override
  int get hashCode => unifiedAddress.hashCode ^ accountUuid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletImportResult &&
          runtimeType == other.runtimeType &&
          unifiedAddress == other.unifiedAddress &&
          accountUuid == other.accountUuid;
}
